function generate_MAT_from_DICOM( input_directory )
%
% This function creates MAT files from
% an input directory with a DICOM directory that contains DICOM 
% images of a cardiac perfusion time series
% and produces the time vector...
%
%         Author: DrZ.
%         Molloi Lab

%% set initial variables...

root_path = input_directory;

% create the MAT directory
[ status, message, messageID ] = mkdir( root_path, 'MAT' );

% get all dicom stack folders
input_directory = [ input_directory '\DICOM\' ];
input_dir = dir( input_directory );

% remove . and .. directories
input_dir( [1,2] ) = [];

% remove files from the list though there shouldn't be any
input_dir = input_dir( [ input_dir.isdir ] );

% sort the list with natsort (external function) to put them in order
input_dir_files = natsort( { input_dir.name } );
sorted_size = size( input_dir_files );

% create a holder for the image time vector
time_vector = zeros( sorted_size(2), 1 );

%% input DICOM stacks and convert

% iterate over the list of directories and input images
for idx1 = 1 : sorted_size(2)
    
    % index to save the MAT files
    file_ID = int2str( idx1 );
    if idx1 < 10
        file_ID = [ '0' file_ID ];
    else
        % do nothing...
    end
                
    % formulate the directory name for dicom import
    dname = input_dir_files{ idx1 };
    % disp( dname );
    dname = [ input_directory filesep dname ];    
    % disp( dname );
    
        % try-catch block to import dicom 
        try
            imStack = ImportDICOMSequence( dname );
        catch exception
            message = sprintf( [ 'Generate MAT:ImportDICOMSequence - Error occured while processing %s.\n Error message: %s. \n' ], ...
                           dname, exception.message );
            disp( message );
            continue
        end
        
        % store the image as double and index... ??
        imStack = double(imStack);
        
        % formulate the name of the MAT file to save
        file_name = [ file_ID '.mat' ];
        input_images{ idx1 } = file_name;
        saved_ID = [ root_path filesep 'MAT' filesep file_name ];
        save( saved_ID, 'imStack' );
  
  % obtain the time from the dicom header information 
  temp_list = dir( [ dname filesep '*.dcm' ] );
  dcm_header = dicominfo( [ dname filesep temp_list(1).name ] );
  temp_time = str2double( dcm_header.ContentTime );
  format long g;
  time_vector( idx1 ) = temp_time;
  
end % end of idx1 loop

timeName = [ 'time_vector_autoGenerated' '.txt' ];
dlmwrite( [ root_path '\' timeName ], time_vector, 'newline', 'pc', 'precision', '%.3f' );

output_text = [ 'MAT and time vector created for: ' root_path ];

disp( output_text );

