% Batch run the RunRegistration script to register all images from multiple
% series.

addpath(genpath('\\polaris\Data4_New\Travis\MATLAB\libsTravis'));
addpath(genpath('\\polaris\Data4_New\Travis\MATLAB\libsFEX'));
addpath(genpath('\\polaris\data4_new\bpziemer\animal_perfusion_data\CardiacWorkflow-dev\Projects\Registration\'));

base = '\\polaris\Data4_New\bpziemer\animal_perfusion_data\03_30_16_data\';


% Define all directories to register here:
base_directories ={...
% [base 'Acq09_Continuous_200mA'],...
[base 'Acq07_Continuous_200mA'],...
[base 'Acq08_Continuous_150mA'],...
[base 'Acq10_Continuous_150mA'],...
[base 'Acq11_Continuous_100mA'],...
[base 'Acq12_Continuous_50mA'],...
[base 'Acq13_Continuous_25mA'],...
[base 'Acq14_Continuous_10mA'],...
[base 'Acq15_Continuous_Baseline'],...
[base 'Acq17_2V_Baseline'],...
[base 'Acq19_2V_Adenosine_0.50'],...
[base 'Acq22_2V_Adenosine_1.0'],...
[base 'Acq24_2V_Adenosine_0.75'],...
[base 'Acq18_Continuous_Adenosine_0.50'],...
[base 'Acq21_Continuous_Adenosine_1.0'],...
[base 'Acq23_Continuous_Adenosine_0.75'],...
[base 'Acq25_Continuous_Adenosine_0.25']...
    };

% % Define master directory to register all others against.
master_dir = [base 'Acq09_Continuous_200mA'];
reference_fname = 'nii35';
RunRegistrationDICOM(base_directories{1}, reference_fname);  % TODO:  Fix this to run within loop.. must run the master volume registration first,
%                                                              %           to generate nii files and such for the master
%                                                              %           volume.

for idx = 1 : numel(base_directories)
    output_text = [ 'Running registration on: ' base_directories{idx} ];
    disp( output_text );
    try
        base_directory = base_directories{idx};
        RunRegistrationDICOM_mod(base_directory, master_dir, reference_fname)
    catch exception
        message = sprintf(['Batch_RunRegistration: Error occured while '...
               'processing %s.\n Error message: %s.'],...
               base_directory, exception.message);
        disp(message);
    end
end
