function [ myo_tac_vec, myo_tac_vec_path ] = load_myo_tac( myo_tac_path, acq_path )

%   load_myo_tac attempts to load the provided myocardial TAC vector from the provided
%   path.  If myo_tac_path points to a volume mask, the volume mask will be
%   loaded and the myo_tac_vec will be generated, afterwhich the newly generated myo_tac will
%   be saved.
%
%   INPUTS:
%
%   myo_tac_path                  STR
%                                 Path to myo vector or myo volume mask
%
%
%   acq_path                      STR
%                                 Path to acquisition of interest.  Include
%                                 REGISTERED if desired                
%
%
%   OUTPUTS:
%
%   myo_tac_vec                   VECTOR(DOUBLE) | (HU)
%                                 Myocardial enhancement curve vector,
%                                 over time
% 
%   myo_tac_path                  STR
%                                 Path of actual MYO_TAC vector loaded.
%
%
%   AUTHOR:       Logan Hubbard
%   DATE CREATED: 05/29/2021
%


err_mode = 'MYO_TAC';
myo_tac_path = verify_path(acq_path, myo_tac_path, err_mode);
myo_tac_var = load_volume(myo_tac_path);
if any(size(size(myo_tac_var)) == 3)
    myo_tac_split_path = strsplit(myo_tac_path, '/');
    myo_tac_vec_path = [acq_path '/' strrep([myo_tac_split_path{end}], '.mat', '') '_autoGenerated.mat'];
    if ~exist(myo_tac_vec_path, 'file')
        myo_tac_vec = gen_aif(acq_path, logical(myo_tac_var));
        saveMAT(myo_tac_vec, myo_tac_vec_path);
    else
        myo_tac_vec = loadMAT(myo_tac_vec_path);
    end
else
    myo_tac_vec = myo_tac_var;
    myo_tac_vec_path = myo_tac_path;
end

end
